/usr/bin/touch /var/lib/texmf/postinstall/texlive-collection-basic-doc_rm.lsr
/usr/libexec/update_tlpdb remove \
amsfonts.doc \
bibtex.doc \
cm.doc \
dvipdfmx.doc \
dvips.doc \
enctex.doc \
etex-pkg.doc \
etex.doc \
graphics-def.doc \
gsftopk.doc \
hyph-utf8.doc \
ifluatex.doc \
ifxetex.doc \
kpathsea.doc \
lua-alt-getopt.doc \
luatex.doc \
makeindex.doc \
metafont.doc \
mflogo.doc \
mfware.doc \
pdftex.doc \
tetex.doc \
tex-ini-files.doc \
texlive-common.doc \
texlive-docindex.doc \
texlive-en.doc \
unicode-data.doc \
xdvi.doc \

